services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-setup:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: >
      sh -c "sleep 20 &&
             kafka-topics.sh --create --topic video-upload --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 &&
             kafka-topics.sh --create --topic video-encoding --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 &&
             kafka-topics.sh --create --topic video-watermarking --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 &&
             kafka-topics.sh --create --topic video-storage --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181"
